### ISSUE TITLE
How do databases work?

### ISSUE THREAD

**Issue by JEnduriumK** [agarcia169/4306-Donaldson-Project#3]
I don't know, I need to find out.

**Comment by JEnduriumK** [comment]
Definitely leaning towards MySQL, considering that's what the Database class is going to be touching.

**Comment by JEnduriumK** [comment]
I wonder if I can run the database on the CSUNIX box, so that it can be accessed by and/or started up by the three of us when needed, so Alex/Bola aren't having to come poke me to start up the DB. Alternatively, we'll need an external hardware host of some kind. 

But if I DO run this on the CSUNIX box, will that be portable in some fashion? Are database files portable?

**Comment by JEnduriumK** [comment]
@Abalogun2 If you can find out how big in bytes a single tweet **pulled from the API** can be, that might be useful information for me to determine how much space our database might need to be. And we'd definitely want to know the full data set. I suspect Twitter attaches account info, time/date info, and possibly other data alongside the actual text of the tweet. Maybe in a JSON format or something. 

At least it might give me an idea on an order of magnitude or something. If the size is small enough, a 100MB database might be reasonable. 

But considering the number of companies involved, I worry that might be too small, and we might need something more in the ballpark of 1GB or even larger for a database. 

If we're ballparking 100MB, it might be doable on the CSUNIX box. I think I have that much (plus more) left in my quota. If it's larger than that, I'll need to plan on it being accessible in some other fashion.  

I'm a little concerned at the idea that we might end up in a situation where @agarcia169 has to just take your code, and... whatever it is I'm doing? and mash them together on his local machine, then use his local machine as a host to do analysis? Which sounds less than ideal, but it might be what we have to fall back to if I can't run this on CSUNIX.

**Comment by Abalogun2** [comment]
i looked into how much data can be in one tweet and this is what my first search gave me was 560 8-bit bytes
source: https://stackoverflow.com/questions/5999821/how-many-bytes-of-memory-is-a-tweet#:~:text=Twitter%20uses%20UTF%2D8%20encoded,%3D%20560%208%2Dbit%20bytes.

**Comment by JEnduriumK** [comment]
@Abalogun2 Just to preface this: 

I don't think this is something that you should or even need to come up with an answer to today? I think it's more an answer you're going to discover as you work on grabbing tweets with the API.

I just wanted to make sure you knew it was information I'd possibly need to construct the database with. Maybe. I don't know.

But there's a few problems there with the link you've provided.

First, that's information that is out of date. It's from when the Twitter character limit was 140 characters, and is referring to the idea that Twitter accepts UTF-8, where every character might be a 32-bit string. Potentially. 

But in the intervening eleven years since that post, [Twitter increased their character limit to 280 characters](https://developer.twitter.com/en/docs/counting-characters). 

But that's _just the Tweet_.

When requesting a series of Tweets via their API, I greatly suspect you get something that may resemble the following:

```csv
username,datestamp,TweetContents,Likes,Retweets,Maybe,Some,Other,Data...
username,datestamp,TweetContents,Likes,Retweets,Maybe,Some,Other,Data...
username,datestamp,TweetContents,Likes,Retweets,Maybe,Some,Other,Data...
username,datestamp,TweetContents,Likes,Retweets,Maybe,Some,Other,Data...
username,datestamp,TweetContents,Likes,Retweets,Maybe,Some,Other,Data...
```
So even if we assume that the 4-octet, UTF-8 thing from eleven years ago still applies (it probably does, but I don't know how safe it is to assume that), then the actual contents of the tweet will max out at **1,120** 8-bit bytes... 

... but then we know this much about the size of the data:

```csv
????,????,1120,????,????,????,????,????,????...
????,????,1120,????,????,????,????,????,????...
????,????,1120,????,????,????,????,????,????...
????,????,1120,????,????,????,????,????,????...
????,????,1120,????,????,????,????,????,????...
```

And I know at a bare minimum we're going to want to at least store the username details, which means storing more than 1,120 bytes per tweet. 

Hopefully that's a little more clear. 

Also, everything I've just said are assumptions dovetailing from eleven year old data. It assumes a blind one-to-one counting of character = character. 

But the link I used above suggests that some multibyte characters may count towards a different number of characters than the number of bytes they are encoded as, and that that information is contained within configuration files for how you access Twitter's API. I think. 

So it could be that one two-byte character actually counts as four characters to them, or something wacky like that, but that also one four-byte character still only counts as one character in some cases? I don't know. So the eventual byte-size maximum of a tweet might actually be more or less than 1,120 bytes.

It's a complicated question.

**Comment by JEnduriumK** [comment]
I think we've settled on a varchar(2048) for now. This is probably overkill. I went for the next biggest power of 2 because... I dunno. 🤷‍♂️
