### ISSUE TITLE
What does Jyotsna need to know?

### ISSUE THREAD

**Issue by agarcia169** [agarcia169/4306-Donaldson-Project#4]
I intend to make this a list of things that we should talk to Dr. Jyotsna about (please add anything if you think of it)
=====================================================
- The excel file of all the twitter handles and profiles that need to be scraped
- update her on the current way we intend to go about this project
- ask her in more detail what data she wants from this project, maybe tell here we don't need an answer immediately so she can think about it

**Comment by JEnduriumK** [comment]
Covered in first meeting about three weeks ago.
